name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.2
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.2

      - name: Build APK
        run: gradle assembleDebug